language: python
cache:
  - apt
  - pip
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8" 
before_install:
  - pip install pipenv --upgrade
script: 
  - pipenv
  - pytest
sudo: false
notifications:
  slack: watchcloud:rNoT5kJJakPqwLSKuev6oa4C
